apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:latest
  replicas: 4
