apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-flask-server
  namespace: test-practise
spec:
  selector:
    matchLabels:
      app: sts-flask
  replicas: 1
  serviceName: "sts-flask-service"
  template:
    metadata:
      labels:
        app: sts-flask
    spec:
      containers:
      - name: container-1
        image: hasmitha25/python-flask:v2
        ports:
        - containerPort: 5000
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
  namespace: test-practise
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: test-flask
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5000
      targetPort: 5000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007


